# █▀█ █▀█ ▀█▀ █ █▀█ █▄ █ █▀
# █▄█ █▀▀  █  █ █▄█ █ ▀█ ▄█

"$schema" = "https://yazi-rs.github.io/schemas/ya$0zi.json"

[mgr]
sort_by        = "alphabetical"
show_hidden    = true 
scrolloff      = 5

[opener]
pdff = [
  { run = 'evince "$@"', desc = "evince", orphan = true},
]

[open]
prepend_rules = [
  { name = "*.pdf", use = "pdff" },
]
